# Autogenerated wrapper script for tree_sitter_modelica_jll for i686-linux-musl
export libtreesitter_modelica

JLLWrappers.@generate_wrapper_header("tree_sitter_modelica")
JLLWrappers.@declare_library_product(libtreesitter_modelica, "libtreesitter_modelica.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_modelica,
        "lib/libtreesitter_modelica.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
