# Autogenerated wrapper script for tree_sitter_modelica_jll for i686-w64-mingw32
export libtreesitter_modelica

JLLWrappers.@generate_wrapper_header("tree_sitter_modelica")
JLLWrappers.@declare_library_product(libtreesitter_modelica, "libtreesitter_modelica.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_modelica,
        "bin\\libtreesitter_modelica.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
